# Generated by Django 4.0.1 on 2022-11-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='creator',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
