# Generated by Django 4.0.1 on 2022-11-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
